filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.template.name: "mylogs"
setup.template.pattern: "mylogs-*"
