apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      file {
        path => "/var/log/containers/order-api.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
      }
    }
    output {
      file { path => "/var/log/logstash/order-api.log" }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
spec:
  selector:
    matchLabels:
      app: order-api
  replicas: 2
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: order-user-project/order-api:V01
          ports:
            - containerPort: 80
          env:
            - name: environment
              value: production
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/containers
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.13.0
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/containers
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: logstash-config
          configMap:
            name: logstash-config
---
# => OrderAPI Service
apiVersion: v1
kind: Service
metadata:
  name: order-api
spec:
  selector:
    app: order-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8011
      nodePort: 30011
---