# => OrderAPI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
spec:
  selector:
    matchLabels:
      app: order-api
  replicas: 2
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: order-user-project/order-api:V01
          ports:
            - containerPort: 8011
---
# filebeat kind:DaemonSet
# => OrderAPI Service
apiVersion: v1
kind: Service
metadata:
  name: order-api
spec:
  selector:
    app: order-api
  type: NodePort
  ports:
    - port: 8011
      targetPort: 8011
      nodePort: 30011
---
# => UserAPI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
spec:
  selector:
    matchLabels:
      app: user-api
  replicas: 2
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: order-user-project/user-api:V01
          ports:
            - containerPort: 8012
---
# => UserAPI Service
apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  selector:
    app: user-api
  type: NodePort
  ports:
    - port: 8012
      targetPort: 8012
      nodePort: 30012
---
# => OrderElastic Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-elastic-deployment
spec:
  selector:
    matchLabels:
      app: order-elastic
  replicas: 2
  template:
    metadata:
      labels:
        app: order-elastic
    spec:
      containers:
        - name: order-elastic
          image: order-user-project/order-elastic:V01
          ports:
            - containerPort: 8013
---
# => OrderElastic Service
apiVersion: v1
kind: Service
metadata:
  name: order-elastic
spec:
  selector:
    app: order-elastic
  type: NodePort
  ports:
    - name: http
      port: 8013
      targetPort: 8013
      nodePort: 30013